import type { PosterTemplate } from "@/lib/poster/templates/types";

/**
 * Event / Career Fair style: gradient background, decorative blobs,
 * left column (title, description, date/time, CTA, contact), right column (3 circular photos).
 * Use with brand colors (primary/secondary/accent) and photo1Url, photo2Url, photo3Url.
 */
export const EVENT_CAREER_FAIR: PosterTemplate = {
  id: "event-career-fair",
  name: "Event / Career Fair (gradient + circular photos)",
  platform: "instagram_post",
  width: 1080,
  height: 1080,
  layers: [
    // Gradient background (dark teal → lighter)
    {
      id: "bg",
      type: "gradient",
      x: 0,
      y: 0,
      width: 1080,
      height: 1080,
      angle: 90,
      colorStops: [
        { offset: 0, color: "#0d3d3d" },
        { offset: 0.5, color: "#0f4a4a" },
        { offset: 1, color: "#0a2e2e" },
      ],
      opacity: 1,
    },

    // Decorative blobs (upper left)
    {
      id: "blob1",
      type: "ellipse",
      x: 220,
      y: 160,
      radiusX: 240,
      radiusY: 140,
      color: "#1a5f5f",
      opacity: 0.35,
    },
    {
      id: "blob2",
      type: "ellipse",
      x: 80,
      y: 340,
      radiusX: 200,
      radiusY: 100,
      color: "#1a5f5f",
      opacity: 0.25,
    },

    // —— Left column: copy ——
    {
      id: "headline",
      type: "text",
      x: 60,
      y: 90,
      width: 460,
      text: "CAREER FAIR",
      fontSize: 72,
      fontStyle: "bold",
      color: "#ffffff",
      lineHeight: 1,
    },
    {
      id: "sub",
      type: "text",
      x: 60,
      y: 200,
      width: 460,
      text: "Don't miss your chance to connect with top employers and explore your career options at our upcoming career fair.",
      fontSize: 26,
      fontStyle: "normal",
      color: "#e2e8f0",
      lineHeight: 1.3,
    },
    {
      id: "date",
      type: "text",
      x: 60,
      y: 380,
      width: 400,
      text: "05.05.2025",
      fontSize: 28,
      fontStyle: "bold",
      color: "#ffffff",
      lineHeight: 1.2,
    },
    {
      id: "time",
      type: "text",
      x: 60,
      y: 430,
      width: 400,
      text: "9:30 AM",
      fontSize: 28,
      fontStyle: "bold",
      color: "#ffffff",
      lineHeight: 1.2,
    },

    // CTA button (rect + text)
    {
      id: "cta_btn",
      type: "rect",
      x: 60,
      y: 500,
      width: 240,
      height: 56,
      color: "#2dd4bf",
      cornerRadius: 28,
      opacity: 1,
    },
    {
      id: "cta",
      type: "text",
      x: 60,
      y: 512,
      width: 240,
      text: "JOIN NOW",
      fontSize: 28,
      fontStyle: "bold",
      color: "#0a2e2e",
      lineHeight: 1.2,
    },

    // Contact block
    {
      id: "phone",
      type: "text",
      x: 60,
      y: 620,
      width: 480,
      text: "123-456-7890",
      fontSize: 22,
      fontStyle: "normal",
      color: "#cbd5e1",
      lineHeight: 1.2,
    },
    {
      id: "website",
      type: "text",
      x: 60,
      y: 665,
      width: 480,
      text: "www.example.com",
      fontSize: 22,
      fontStyle: "normal",
      color: "#cbd5e1",
      lineHeight: 1.2,
    },
    {
      id: "address",
      type: "text",
      x: 60,
      y: 710,
      width: 480,
      text: "123 Anywhere St., Any City",
      fontSize: 22,
      fontStyle: "normal",
      color: "#cbd5e1",
      lineHeight: 1.2,
    },

    // —— Right column: 3 circular photos (stacked, slight overlap) ——
    {
      id: "photo1",
      type: "image",
      x: 650,
      y: 150,
      width: 260,
      height: 260,
      srcKey: "photo1",
      fit: "cover",
      clip: "circle",
    },
    {
      id: "photo2",
      type: "image",
      x: 690,
      y: 410,
      width: 260,
      height: 260,
      srcKey: "photo2",
      fit: "cover",
      clip: "circle",
    },
    {
      id: "photo3",
      type: "image",
      x: 650,
      y: 670,
      width: 260,
      height: 260,
      srcKey: "photo3",
      fit: "cover",
      clip: "circle",
    },
  ],
};
